export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const INIT_INGREDIENT = "INIT_INGREDIENT";
export const ERROR = "ERROR";
export const ORDER_HANDLER = "ORDER_HANDLER";
export const ORDER_FAILED = "ORDER_FAILED";
export const LOADING = "LOADING";
export const PURCHASED = "PURCHASED";
// export const PRICE_FETCH = "PRICE_FETCH";
